version: "3"

services:
    packrat-client:
        container_name: packrat-client
        image: packrat-client
        restart: always
        build:
            context: .
            dockerfile: ./docker/client.Dockerfile
        env_file:
            - .env
        ports:
            - $PACKRAT_CLIENT_PORT:3000
        volumes:
            - ./client:/app/client
            - ./common:/app/common

    packrat-server:
        container_name: packrat-server
        image: packrat-server
        restart: always
        build:
            context: .
            dockerfile: ./docker/server.Dockerfile
        env_file:
            - .env
        ports:
            - $PACKRAT_SERVER_PORT:4000
        volumes:
            - ./server:/app/server
            - ./common:/app/common
        depends_on:
            - db

    db:
        container_name: packrat-db
        image: mariadb:10.5
        restart: always
        ports:
            - $PACKRAT_DB_PORT:3306
        env_file:
            - .env
