version: "3.4"

services:
    packrat-proxy:
        container_name: packrat-proxy
        image: packrat-proxy
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: proxy
        depends_on:
            - packrat-client
            - packrat-server
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    packrat-client:
        container_name: packrat-client
        image: packrat-client
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: client
        env_file:
            - .env
        ports:
            - $PACKRAT_CLIENT_PORT:3000
        volumes:
            - ./node_modules:/app/node_modules
            - ./package.json:/app/package.json
            - ./client:/app/client
            - ./common:/app/common

    packrat-server:
        container_name: packrat-server
        image: packrat-server
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: server
        env_file:
            - .env
        ports:
            - $PACKRAT_SERVER_PORT:4000
        volumes:
            - ./node_modules:/app/node_modules
            - ./package.json:/app/package.json
            - ./server:/app/server
            - ./common:/app/common
        depends_on:
            - db

    db:
        container_name: packrat-db
        image: mariadb:10.5
        restart: always
        ports:
            - $PACKRAT_DB_PORT:3306
        env_file:
            - .env
