version: "3"

services:
    packrat-proxy:
        image: nginx:1.17.10
        container_name: packrat-proxy
        depends_on:
            - packrat-client
            - packrat-server
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    client:
        container_name: client
        image: client
        restart: always
        build:
            context: .
            dockerfile: ./docker/client.Dockerfile
        env_file:
            - .env
        ports:
            - ${PACKRAT_CLIENT_PORT:-3000}
        volumes:
            - ./client:/app/client
            - ./common:/app/common
        depends_on:
            - db

    server:
        container_name: server
        image: server
        restart: always
        build:
            context: .
            dockerfile: ./docker/server.Dockerfile
        env_file:
            - .env
        ports:
            - ${PACKRAT_SERVER_PORT:-4000}
        volumes:
            - ./server:/app/server
            - ./common:/app/common
        depends_on:
            - db

    db:
        container_name: packrat-db
        image: mariadb:10.5
        restart: always
        ports:
            - 3306:3306
        env_file:
            - .env
