version: "3.4"

services:
    packrat-proxy:
        container_name: packrat-proxy
        image: nginx:1.17.10
        restart: always
        build:
            context: .
            dockerfile: ./docker/prod.Dockerfile
            target: proxy
        depends_on:
            - packrat-client
            - packrat-server
        ports:
            - 80:80

    packrat-client:
        container_name: packrat-client
        image: packrat-client
        restart: always
        build:
            context: .
            dockerfile: ./docker/prod.Dockerfile
            target: client
        env_file:
            - .env
        ports:
            - $PACKRAT_CLIENT_PORT:3000

    packrat-server:
        container_name: packrat-server
        image: packrat-server
        restart: always
        build:
            context: .
            dockerfile: ./docker/prod.Dockerfile
            target: server
        env_file:
            - .env
        ports:
            - $PACKRAT_SERVER_PORT:4000
        depends_on:
            - db

    db:
        container_name: packrat-db
        image: mariadb:10.5
        restart: always
        ports:
            - $PACKRAT_DB_PORT:3306
        env_file:
            - .env
