version: "3.4"

services:
    packrat-proxy:
        container_name: packrat-proxy
        image: packrat-proxy
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: proxy
        depends_on:
            - packrat-client
            - packrat-server
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    packrat-client:
        container_name: packrat-client
        image: packrat-client
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: client
        ports:
            - $PACKRAT_CLIENT_PORT:3000
        environment:
            - NODE_ENV=$NODE_ENV
            - REACT_APP_SERVER_ENDPOINT=$REACT_APP_SERVER_ENDPOINT
        volumes:
            - ./node_modules:/app/node_modules
            - ./package.json:/app/package.json
            - ./client:/app/client

    packrat-server:
        container_name: packrat-server
        image: packrat-server
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: server
        ports:
            - $PACKRAT_SERVER_PORT:4000
        environment:
            - NODE_ENV=$NODE_ENV
            - CLIENT_ENDPOINT=$CLIENT_ENDPOINT
            - DATABASE_URL=$DATABASE_URL
            - SESSION_SECRET=$SESSION_SECRET
            - EDAN_AUTH_KEY=$EDAN_AUTH_KEY
            - EDAN_SERVER=$EDAN_SERVER
            - EDAN_APPID=$EDAN_APPID
            - OCFL_STORAGE_ROOT=$OCFL_STORAGE_ROOT
            - OCFL_STAGING_ROOT=$OCFL_STAGING_ROOT
        volumes:
            - ./node_modules:/app/node_modules
            - ./package.json:/app/package.json
            - ./server:/app/server
        depends_on:
            - db

    db:
        container_name: packrat-db
        image: packrat-db
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
            target: db
        ports:
            - $PACKRAT_DB_PORT:3306
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        volumes:
            - ./server/db/sql:/app/

    packrat-solr:
        container_name: packrat-solr
        image: packrat-solr
        restart: always
        build:
            context: .
            dockerfile: ./docker/solr.Dockerfile
            target: solr
        ports:
            - $PACKRAT_SOLR_PORT:8983
        env_file:
            - .env
networks:
    default:
        ipam:
            config:
                - subnet: 192.168.4.0/24
