version: "3.4"

services:
    packrat-proxy:
        container_name: packrat-proxy
        image: packrat-proxy
        restart: always
        build:
            context: ../..
            dockerfile: ./conf/docker/proxy-prod.Dockerfile
            target: proxy
        depends_on:
            - packrat-client
            - packrat-server
        ports:
            - $PACKRAT_PROXY_PORT:80

    packrat-client:
        container_name: packrat-client
        image: packrat-client
        restart: always
        build:
            context: ../..
            dockerfile: ./conf/docker/client-prod.Dockerfile
            target: client
        ports:
            - $PACKRAT_CLIENT_PORT:3000
        environment:
            - NODE_ENV=$NODE_ENV
            - REACT_APP_SERVER_ENDPOINT=$REACT_APP_SERVER_ENDPOINT

    packrat-server:
        container_name: packrat-server
        image: packrat-server
        restart: always
        build:
            context: ../..
            dockerfile: ./conf/docker/server-prod.Dockerfile
            target: server
        ports:
            - $PACKRAT_SERVER_PORT:4000
        environment:
            - NODE_ENV=$NODE_ENV
            - CLIENT_ENDPOINT=$CLIENT_ENDPOINT
            - DATABASE_URL=$DATABASE_URL
            - SESSION_SECRET=$SESSION_SECRET
            - EDAN_AUTH_KEY=$EDAN_AUTH_KEY
            - EDAN_SERVER=$EDAN_SERVER
            - EDAN_APPID=$EDAN_APPID
            - OCFL_STORAGE_ROOT=$OCFL_STORAGE_ROOT
            - OCFL_STAGING_ROOT=$OCFL_STAGING_ROOT
            - PACKRAT_SOLR_HOST=$PACKRAT_SOLR_HOST
            - COOK_SERVER_URL=$COOK_SERVER_URL

        depends_on:
            - db

    db:
        container_name: packrat-db
        image: mariadb:10.5
        restart: always
        ports:
            - $PACKRAT_DB_PORT:3306
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

    packrat-solr:
        container_name: packrat-solr
        image: packrat-solr
        restart: always
        build:
            context: ../..
            dockerfile: ./conf/docker/solr.Dockerfile
            target: solr
        ports:
            - $PACKRAT_SOLR_PORT:8983

networks:
    default:
        ipam:
            config:
                - subnet: 192.168.4.0/24
