USE `Packrat`;

-- Keep the order of VocabularySet items in sync with the order of Vocabulary items, which makes use of idVocabularySet
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.CaptureMethod', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.DatasetType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.ItemPositionType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.FocusType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.LightSourceType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.BackgroundRemovalMethod', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureData.ClusterType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('CaptureDataFile.VariantType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('Model.CreationMethod', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('Model.Modality', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('Model.Units', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('Model.Purpose', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('ModelGeometryFile.ModelFileType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('ModelProcessingActionStep.ActionMethod', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('ModelUVMapChannel.UVMapType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('Identifier.IdentifierType', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('Metadata.MetadataSource', 1);
INSERT INTO VocabularySet (Name, SystemMaintained) VALUES ('WorkflowStep.WorkflowStepType', 1);

-- Keep the order of VocabularySet items in sync with the order of Vocabulary items, which makes use of idVocabularySet
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (1, 1, 'Photogrammetry');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (1, 2, 'CT');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (1, 3, 'Structured Light');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (1, 4, 'Laser Line');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (1, 5, 'Spherical Laser');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (2, 1, 'Photogrammetry Image Set');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (2, 2, 'Grey Card Image Set');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (2, 3, 'Color Card Image Set');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (2, 4, 'Background Removal Image Set');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (2, 5, 'Calibration Dataset');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (3, 1, 'Relative To Environment');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (3, 2, 'Relative To Turntable');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (4, 1, 'Fixed');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (4, 2, 'Variable');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (5, 1, 'Ambient');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (5, 2, 'Strobe Standard');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (5, 3, 'Strobe Cross');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (5, 4, 'Patterned/Structured');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (6, 1, 'None');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (6, 2, 'Clip Black');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (6, 3, 'Clip White');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (6, 4, 'Background Subtraction By Capture Dataset Set');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (7, 1, 'None');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (7, 2, 'Array');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (7, 3, 'Spherical Image Station');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (7, 4, 'Focal Stack Position Based');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (7, 5, 'Focal Stack Focus Based');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (8, 1, 'Raw');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (8, 2, 'Processed');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (8, 3, 'Processed, Zeroed');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (8, 4, 'From Camera');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (9, 1, 'Scan To Mesh');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (9, 2, 'CAD');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (10, 1, 'Point Cloud');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (10, 2, 'Mesh');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 1, 'Micrometer');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 2, 'Millimeter');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 3, 'Centimeter');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 4, 'Meter');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 5, 'Kilometer');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 6, 'Inch');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 7, 'Foot');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 8, 'Yard');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 9, 'Mile');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (11, 10, 'Astronomical Unit');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (12, 1, 'Master');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (12, 2, 'Web Delivery');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (12, 3, 'Print Delivery');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (12, 4, 'Intermediate Processing Step');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 1, 'obj - Alias Wavefront Object');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 2, 'ply - Stanford Polygon File Format');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 3, 'stl - StereoLithography');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 4, 'glb - GL Transmission Format Binary');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 5, 'gltf - GL Transmission Format');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 6, 'usdz - Universal Scene Description (zipped)');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 7, 'x3d');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 8, 'wrl - VRML');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 9, 'dae - COLLADA');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 10, 'fbx - Filmbox');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 11, 'ma - Maya');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 12, '3ds - 3D Studio');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 13, 'ptx');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (13, 14, 'pts');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 1, 'Normal: Tangent Space');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 2, 'Normal: Object Space');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 3, 'Ambient Occlusion');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 4, 'Photo Texture');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 5, 'Hole Fill');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 6, 'Transparency');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 7, 'Specular');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 8, 'Roughness');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 9, 'Metalness');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 10, 'BRDF');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 11, 'Reflection');
INSERT INTO Vocabulary (idVocabularySet, SortOrder, Term) VALUES (14, 12, 'Refraction');