name: Lint, Test and Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for lint errors
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: Packrat
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup test DB
        run: mysql -h 127.0.0.1 -v -P 3306 -u root --password=test < server/db/sql/scripts/Packrat.sql

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test
        env:
          DATABASE_URL: mysql://root:test@localhost:3306/Packrat

  build-dev:
    if: github.event_name == 'push' && contains(github.ref, 'develop')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current package version
        id: dev-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: Build dev server
        uses: docker/build-push-action@v1.1.0
        with:
          repository: packrat/server-dev
          tags: ${{ steps.dev-version.outputs.current-version }}
          dockerfile: docker/dev.Dockerfile
          target: server
          push: false

      - name: Build dev client
        uses: docker/build-push-action@v1.1.0
        with:
          repository: packrat/client-dev
          tags: ${{ steps.dev-version.outputs.current-version }}
          dockerfile: docker/dev.Dockerfile
          target: client
          push: false

      - name: Build dev proxy
        uses: docker/build-push-action@v1.1.0
        with:
          repository: packrat/proxy-dev
          tags: ${{ steps.dev-version.outputs.current-version }}
          dockerfile: docker/dev.Dockerfile
          target: proxy
          push: false

  build-prod:
    if: github.event_name == 'push' && contains(github.ref, 'master')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current package version
        id: prod-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: Build prod server
        uses: docker/build-push-action@v1.1.0
        with:
          repository: packrat/server-prod
          tags: ${{ steps.prod-version.outputs.current-version }}
          dockerfile: docker/prod.Dockerfile
          target: server
          push: false

      - name: Build prod client
        uses: docker/build-push-action@v1.1.0
        with:
          repository: packrat/client-prod
          tags: ${{ steps.prod-version.outputs.current-version }}
          dockerfile: docker/prod.Dockerfile
          target: client
          push: false

      - name: Build prod proxy
        uses: docker/build-push-action@v1.1.0
        with:
          repository: packrat/proxy-prod
          tags: ${{ steps.prod-version.outputs.current-version }}
          dockerfile: docker/prod.Dockerfile
          target: proxy
          push: false

