# CI setup for Packrat
#
# Lints and Tests code for pull requests
# Builds after tests pass on push/merge to master or develop branch

name: Lint, Test and Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for lint errors
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    services:
      # MariaDB service for test database
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: Packrat
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup test DB
        run: mysql -h 127.0.0.1 -v -P 3306 -u root --password=test < server/db/sql/scripts/Packrat.sql

      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies in CI mode
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests using test DB
      - name: Run Tests
        run: yarn test
        env:
          DATABASE_URL: mysql://root:test@localhost:3306/Packrat

  build:
    # Only run this step on push to specified branches (PR merge counts as push too)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    env: # Ideally this will be stored in github secrets and will be accessed via ${{ secrets.* }}
      PACKRAT_CLIENT_PORT: 3000
      PACKRAT_SERVER_PORT: 4000
      PACKRAT_DB_PORT: 3306
      MYSQL_ROOT_PASSWORD: packrat
      REACT_APP_SERVER_ENDPOINT: http://packrat-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current package version
        id: packrat-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      # Runs commands pre-build
      # Ideally .env will be created from secrets ${{ secrets.DEV/PROD_ENV }} > .env
      - name: Prepare build
        run: touch .env

      - name: Build Dev images
        run: docker-compose -f docker-compose.dev.yml build
        if: contains(github.ref, 'develop')

      - name: Build Prod images
        run: docker-compose -f docker-compose.prod.yml build
        if: contains(github.ref, 'master')

      # Prepares tag for docker images
      - name: Prepare image tag
        id: prepare-tag
        run: if [ ${{ contains(github.ref, 'master') }} = true ]; then echo "::set-output name=tag::prod"; else echo "::set-output name=tag::dev"; fi

      # Tags images with "image:stage-version" eg. dev:1.0.0
      - name: Tag images
        run: |
          echo Tagging with ${{ steps.prepare-tag.outputs.tag }}-${{ steps.packrat-version.outputs.current-version }}
          docker tag packrat-server:latest packrat-server:${{ steps.prepare-tag.outputs.tag }}-${{ steps.packrat-version.outputs.current-version }}
          docker tag packrat-client:latest packrat-client:${{ steps.prepare-tag.outputs.tag }}-${{ steps.packrat-version.outputs.current-version }}
          docker tag packrat-proxy:latest packrat-proxy:${{ steps.prepare-tag.outputs.tag }}-${{ steps.packrat-version.outputs.current-version }}

      # Runs commands post-build
      - name: Build cleanup
        run: |
          echo Cleaning up redundant tags
          docker rmi packrat-server:latest packrat-client:latest packrat-proxy:latest
          docker images

      # Pushes built images to container registry
      - name: Push images
        run: echo Pushing images to container registry...
